import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import ConvexClientProvider from "@/providers/convex-client-provider";
import ModalProvider from "@/providers/modal-provider";

export const metadata: Metadata = {
	title: "SketchHive",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ConvexClientProvider>
					<Toaster
						toastOptions={{
							classNames: {
								error: "bg-red-200 text-red-950",
								success: "bg-green-200 text-green-950",
								warning: "bg-yellow-200 text-yellow-950",
								info: "bg-blue-200 text-blue-950",
							},
						}}
					/>
					<ModalProvider />
					{children}
				</ConvexClientProvider>
			</body>
		</html>
	);
}
